// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1:string):Promise<void>;

export function GetProfilesDirectory():Promise<string>;

export function ListProfiles():Promise<Array<string>>;

export function LoadProfile(arg1:string):Promise<void>;

export function ProfileExists(arg1:string):Promise<boolean>;

export function SaveProfile(arg1:string):Promise<void>;

export function TurnOffMonitors():Promise<void>;
