// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetProfilesDirectory() {
  return window['go']['main']['App']['GetProfilesDirectory']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadProfile(arg1) {
  return window['go']['main']['App']['LoadProfile'](arg1);
}

export function ProfileExists(arg1) {
  return window['go']['main']['App']['ProfileExists'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function TurnOffMonitors() {
  return window['go']['main']['App']['TurnOffMonitors']();
}
